### ISSUE TITLE
empty result.fa

### ISSUE THREAD

**Issue by LisaBlazek** [ruiguo-bio/replong#10]
hello!
i run replong with the drosophila test file 
/software/BIN/replong -f dro_100k.fa -s 100M -t data/ -c true -h 4 -e 16 2>&1 | tee replong.log
and got an empty result.fa
[replong.log](https://github.com/ruiguo-bio/replong/files/2624534/replong.log)
i'm new to bioinformatics so i don't really know what i did wrong here
kind regards,
lisa

**Comment by bzvew** [comment]
Hi Lisa. Can you attach your input fasta file to google drive? I'd like to test that if you can give me a link to your input file.

Rui

**Comment by LisaBlazek** [comment]
hello!
i used the drosophila test file you supplied in the tutorial
https://drive.google.com/open?id=0B90UmIY8m2PYcTl6WVpyQmdfM3c
kind regards,
lisa

**Comment by bzvew** [comment]
Hi Liza. I think it may relate to faidx. Can you attach the new.fa in the folder /project/bvortho/lblazek/repeat_analysis/RepLong_test 

I think your pip is linked to pip2? If possible, you can try pip uninstall pyfaidx and then pip3 install pyfaidx, and try again.

**Comment by LisaBlazek** [comment]
hello!
here is the new.fa
[new.fa.tar.gz](https://github.com/ruiguo-bio/replong/files/2652434/new.fa.tar.gz)
kind regards, 
lisa

**Comment by bzvew** [comment]
Hi, Liza. The difference between your running and mine is the number the thread and the pyfaidx version. I don't limit the thread number to 4 and my pyfaidx is installed by pip3 and it's version is 0.4.7.1. Now I'm running the same thing (-h 4) and switched to the latest pyfaidx version. It takes time(only 4 threads), and I hope to find out what happened.

**Comment by bzvew** [comment]
Hi Liza. I find the faidx version is the reason for that empty file. You can use `pip install pyfaidx==0.4.7.1` to fix that issue.

**Comment by LisaBlazek** [comment]
hello!
our sysadmin changed the version, but still i get an empty result file.
                 $ /software/BIN/replong -f human_100k.fa -s 500M -t /tmp/lblazek/replong/jan04
[log.txt](https://github.com/ruiguo-bio/replong/files/2727054/log.txt)
for this i used the human data you provided!
kind regards,
lisa

**Comment by bzvew** [comment]
Hi Liza,

Have you tried the drosophila data after the install faidx 0.4.7.1? I'd like to make sure the drosophila data work first.

**Comment by LisaBlazek** [comment]
yes i did! it did not work so i tried the human data as well

**Comment by bzvew** [comment]
Hi, could you attach the latest drosophila log.txt?

**Comment by LisaBlazek** [comment]
sorry here is it!
[dec13_replong.log](https://github.com/ruiguo-bio/replong/files/2745025/dec13_replong.log)
kind regards, lisa

**Comment by bzvew** [comment]
Hi, I think it's an issue with python. Could you run a test on that server? In terminal run python, and then 
try to run
`import sys`
to see if there is any issue for just a simple import.

**Comment by LisaBlazek** [comment]
hello!
i could run it without problems!

**Comment by ruiguo-bio** [comment]
Hi Lisa. Could you first pull the latest code, then
`cd tmp/lblazek/replong/dec13/`
`python /software/RepLong/replong/edge_1.py all.ovl temp/correction/step2.gkpStore/reads.txt 250 200 0.96 new.edge` 
I add some debug info into the code, and I'd like to know what is the result this time.

**Comment by LisaBlazek** [comment]
sorry for the super long response time, i was off.
it worked now thank you very much!
