### ISSUE TITLE
canu failed with 'gatekeeper store exists, but contains no reads'.

### ISSUE THREAD

**Issue by maoying0423** [ruiguo-bio/replong#12]
Hi,
I tried to run the human_100k.fa file in Replong to find the repeat sequence, but the following problem

Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'gatekeeper store exists, but contains no reads'.

temp/correction/1-overlapper/001/*.ovb
ERROR:  invalid arg 'temp/correction/1-overlapper/001/*.ovb'
usage: /home/maoying/software/canu/replong/canu/Linux-amd64/bin/overlapConvert [options] file.ovb[.gz]

  -G             gkpStore (needed for -coords, the default)

  -coords        output coordiantes on reads
  -hangs         output hangs on reads
  -raw           output raw hangs on reads

  -native        input ovb file is NOT snappy compressed

ERROR:  no overlap files supplied
filter overlap file to merge repeat
ovlfile is:  all.ovl
lengthfile is:  temp/correction/step2.gkpStore/reads.txt
fromlength is:  250
lendiff is:  200
ratio is:  0.96
output_edge is:  new.edge
Traceback (most recent call last):
  File "/home/maoying/software/canu/replong/edge_1.py", line 93, in <module>
    outfilename)
  File "/home/maoying/software/canu/replong/edge_1.py", line 9, in buildEdgeWithFrom
    with open(overlapfile, 'r') as a, open(readlengthfile, 'r') as b,\
FileNotFoundError: [Errno 2] No such file or directory: 'temp/correction/step2.gkpStore/reads.txt'
use community detection to merge repeat

载入程辑包：‘igraph’

The following objects are masked from ‘package:stats’:

    decompose, spectrum

The following object is masked from ‘package:base’:

    union

Error in file(file, "rt") : 无法打开链结
Calls: read.table -> file
此外: Warning message:
In file(file, "rt") : 无法打开文件'new.edge': 没有那个文件或目录
停止执行
split: 无法打开'new.line' 读取数据: 没有那个文件或目录
ls: 无法访问'new_*.line': 没有那个文件或目录
ls: 无法访问'new_*.sed': 没有那个文件或目录
ls: 无法访问'new_*.bed': 没有那个文件或目录
ls: 无法访问'new_*_sorted.bed': 没有那个文件或目录
Find original read names
cat: 'new_*.name': 没有那个文件或目录
cat: 'new_*_sorted.bed': 没有那个文件或目录
extract repeat sequences
Traceback (most recent call last):
  File "/home/maoying/miniconda3/bin//faidx", line 8, in <module>
    sys.exit(main())
  File "/home/maoying/miniconda3/lib/python3.7/site-packages/pyfaidx/cli.py", line 168, in main
    write_sequence(args)
  File "/home/maoying/miniconda3/lib/python3.7/site-packages/pyfaidx/cli.py", line 16, in write_sequence
    fasta = Fasta(args.fasta, default_seq=args.default_seq, strict_bounds=not args.lazy, split_char=args.delimiter, filt_function=filt_function)
  File "/home/maoying/miniconda3/lib/python3.7/site-packages/pyfaidx/__init__.py", line 658, in __init__
    sequence_always_upper=sequence_always_upper)
  File "/home/maoying/miniconda3/lib/python3.7/site-packages/pyfaidx/__init__.py", line 306, in __init__
    self.build_index()
  File "/home/maoying/miniconda3/lib/python3.7/site-packages/pyfaidx/__init__.py", line 399, in build_index
    valid_entry = check_bad_lines(rname, bad_lines, i)  # advance index since we're at the end of the file
UnboundLocalError: local variable 'i' referenced before assignment
the file before merging is new.fa
the result file name is result.fa
I followed all the instructions on your page, but the problem seems to have arisen anyway
Thank you very much

**Comment by maoying0423** [comment]
This is the test.log generated at runtime
[test.log](https://github.com/ruiguo-bio/replong/files/4980577/test.log)

**Comment by ruiguo-bio** [comment]
Hello. Thank you for reporting that. I fix that issue caused by awk version and please pull the new code, and you can run your old command again in the same folder to reduce the computing time for canu.

**Comment by maoying0423** [comment]
Thank you very much for your help
