### ISSUE TITLE
Is all.out supposed to be all.ovl?

### ISSUE THREAD

**Issue by rsharris** [ruiguo-bio/replong#6]
In processRead.sh, at lines 420..429, the file all.OUT is deleted, and then the results of overlapConvert are appended to the file all.OVL.

I can't find all.OUT used anywhere else.  If that was intended to be all.OVL, then if the user runs replong more than once all.OVL will contain leftovers from early runs.

OR at least I guess that's what happens.  After running replong I can't find all.ovl, yet I don't see anything in the scripts that would delete it.  And I do see one file listed by the echo $i at line 427, so all.ovl should have been created at that point.

**Comment by bzvew** [comment]
Yes, your first guess is correct. I change that to all.ovl now.
