### ISSUE TITLE
"GNU split" requirement is misleading.

### ISSUE THREAD

**Issue by rsharris** [ruiguo-bio/replong#7]
It's not that GUN split is required.  GNU split didn't originally support --additional-suffix.  I don't know when it was added, but a user can have GNU split but if it's an older version she is out of luck.

**Comment by rsharris** [comment]
I found at least one reference that said that option was added in version 8.16.  No idea if that is correct.

**Comment by bzvew** [comment]
I add the 8.16 version requirement now.
